### ISSUE TITLE
Support other options for resolve?

### ISSUE THREAD

**Issue by phated** [gulpjs/evented-require#3]
I was looking at the `resolve` module and it has some cool options (nothing we currently use but `opts.extensions` looked interesting).  Should this module support all of them?

**Comment by sttk** [comment]
Some options accept functions. Does these behave weirdly or badly for this module? (though I didn't check them at all.)
On the other hand, I'm interested in those `opts.preserveSymlinks` and `opts.moduleDirectory` options, too. If my memory is correct, there were issues about them.

**Comment by phated** [comment]
I can switch the `basedir` parameter to `opts` and pass them directly to `resolve.sync()`.  Should I do that?

**Comment by sttk** [comment]
Yeah. I think it's good.

**Comment by phated** [comment]
Closing in favor of #5
